// <auto-generated />
namespace AmdmProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddaccordLinkfieldtoAccordtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddaccordLinkfieldtoAccordtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201610081120083_Add accordLink field to Accord table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
